import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const exo = localFont({
  src: [
    {
      path: "./fonts/ExoSpace.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-exo",
})

export const metadata: Metadata = {
  title: "SupraVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.variable}>
        {children}
      </body>
    </html>
  );
}
